////////////////////////////////////////////////////////////////////////////////////
// $Revision: 38578 $
////////////////////////////////////////////////////////////////////////////////////
// Copyright 2010 SlickEdit Inc.
////////////////////////////////////////////////////////////////////////////////////
#ifndef VS_MESSAGE_DEFS_H
#define VS_MESSAGE_DEFS_H

#define MESSAGE_NOT_AVAILABLE_RC	0
#define FILE_NOT_FOUND_RC	-2
#define PATH_NOT_FOUND_RC	-3
#define TOO_MANY_OPEN_FILES_RC	-4
#define ACCESS_DENIED_RC	-5
#define MEMORY_CONTROL_BLOCKS_RC	-7
#define INSUFFICIENT_MEMORY_RC	-8
#define INVALID_DRIVE_RC	-15
#define NO_MORE_FILES_RC	-18
#define DISK_IS_WRITE_PROTECTED_RC	-19
#define UNKNOWN_UNIT_RC	-20
#define DRIVE_NOT_READY_RC	-21
#define BAD_DEVICE_COMMAND_RC	-22
#define DATA_ERROR_RC	-23
#define BAD_REQUEST_STRUCTURE_LENGTH_RC	-24
#define SEEK_ERROR_RC	-25
#define UNKNOWN_MEDIA_TYPE_RC	-26
#define SECTOR_NOT_FOUND_RC	-27
#define PRINTER_OUT_OF_PAPER_RC	-28
#define WRITE_FAULT_RC	-29
#define READ_FAULT_RC	-30
#define GENERAL_FAILURE_RC	-31
#define ERROR_OPENING_FILE_RC	-32
#define ERROR_READING_FILE_RC	-33
#define ERROR_WRITING_FILE_RC	-34
#define ERROR_CLOSING_FILE_RC	-35
#define INSUFFICIENT_DISK_SPACE_RC	-36
#define PROGRAM_CAN_NOT_BE_RUN_IN_OS2_RC	-37
#define ERROR_CREATING_DIRECTORY_RC	-38
#define SESSION_PARENT_EXISTS_RC	-39
#define PIF_FILE_NOT_FOUND_RC	-40
#define BAD_PIF_FILE_RC	-41
#define UNABLE_TO_CREATE_PIF_FILE_RC	-42
#define UNABLE_TO_OPEN_ERROR_CODE_TEMP_FILE_RC	-43
#define UNABLE_TO_OPEN_PIF_TEMP_FILE_RC	-44
#define BAD_ERROR_CODE_TEMP_FILE_RC	-45
#define INVALID_EXECUTABLE_FORMAT_RC	-46
#define SYSTEM_FAILED_TO_EXECUTE_PROGRAM_RC	-47
#define WDOSRC_FILE_NOT_FOUND_RC	-48
#define FIOERROR_CREATING_TIMER_RC	-49
#define FIOBREAK_KEY_PRESSED_RC	-50
#define SLKSHELL_FILE_NOT_FOUND_RC	-51
#define FIOINVALID_ARGUMENT_RC	-52
#define EOF_RC	-53
#define ARGFILE_NOT_FOUND_RC -54
#define ARGACCESS_DENIED_RC -55
#define ARGPATH_NOT_FOUND_RC -56
#define ARGUNABLE_TO_OPEN_FILE_RC -57
#define MEMBER_IN_USE_RC -58
#define DATASET_IN_USE_RC -59
#define DATASET_OR_MEMBER_IN_USE_RC -60
#define VOLUME_OUT_OF_SPACE_RC -61
#define DATASET_OUT_OF_EXTENT_RC -62
#define PDS_DIR_OUT_OF_SPACE_RC -63
#define DATASET_IO_RC -64
#define UNSUPPORTED_DATASET_TYPE_RC -65
#define DATASET_NOT_PDS_RC -66
#define PDS_MEMBER_NOT_FOUND_RC -67
#define NO_MORE_DDNAME_RC -68
#define UNABLE_TO_ALLOCATE_DDNAME_TO_DATASET_RC -69
#define DATASET_NOT_SEQUENTIAL_RC -70
#define UNSUPPORTED_DATASET_OPERATION_RC -71
#define INVALID_DATASET_NAME_RC -72
#define INVALID_PDS_MEMBER_NAME_RC -73
#define INSUFFICIENT_ACCESS_TO_DATASET_RC -74
#define UNABLE_TO_UPDATE_PDS_MEMBER_DIRECTORY_RC -75
#define INVALID_DATASET_PASSWORD_RC -76
#define DATASET_NOT_FOUND_RC -77
#define CANT_ACCESS_INTERNAL_READER_RC -78
#define CANT_WRITE_TO_SYSLOG_RC -79
#define CANT_LOAD_ASSEMBLER_MODULES_RC -80
#define CANT_QUERY_SYSTEM_DATASET_LISTING_RC -81
#define INSUFFICIENT_SPILL_DISK_SPACE_RC -82
#define INSUFFICIENT_LOG_DISK_SPACE_RC -83
#define USER_LOG_TOO_LARGE_RC -84
#define URL_BAD_RC -85
#define URL_PROTO_NOT_SUPPORTED_RC -86
#define URL_ERROR_READING_RESPONSE_RC -87
#define URL_STATUS_RC -88
#define URL_MOVED_RC -89
#define URL_RESPONSE_NOT_SUPPORTED_RC -90
#define BUFFER_OVERFLOW_RC -92
#define VSRC_OPERATION_CANCELLED -95
#define VSRC_OPERATION_NOT_FINISHED -96
#define VSRC_POTENTIAL_DEADLOCK_DETECTED -97

#define SOCK_BAD_HOST_RC -103
#define SOCK_BAD_PORT_RC -106

#define NOT_ENOUGH_MEMORY_RC -2029
#define COMMAND_CANCELLED_RC -2038
#define FUNCTION_NOT_AVAILABLE_RC -2113

#define INVALID_REGULAR_EXPRESSION_RC	-2500
#define EOL1_RC	-2501
#define EOL2_RC	-2502
#define RE_EOF_RC	-2503
#define REBREAK_KEY_PRESSED_RC	-2504

#define INCORRECT_VERSION_RC -3000
#define INVALID_ARGUMENT_RC -3015
#define STRING_NOT_FOUND_RC -3022
#define INVALID_POINTER_ARGUMENT_RC -3073

#define JAVA_JAR_INCOMPLETE_HEADER_RC -4133
#define JAVA_JAR_BAD_MAGIC_NUMBER_RC -4134
#define JAVA_JAR_UNSUPPORTED_VERSION_RC -4135
#define JAVA_JAR_DECOMPRESS_ERROR_RC -4136
#define JAVA_JAR_CORRUPT_HEADER_RC -4137

#endif // VS_MESSAGE_DEFS_H
